###*
# 200 (OK) Response
#
# Usage:
# return res.ok();
# return res.ok(data);
# return res.ok(data, 'auth/login');
#
# @param  {Object} data
# @param  {String|Object} options
#          - pass string to render specified view
###
module.exports = (data, options, sendSocket = false) ->
# Get access to `req`, `res`, & `sails`
  req = @req
  res = @res
  sails = req._sails
  sails.log.silly 'res.ok() :: Sending 200 ("OK") response'
  # Set status code
  res.status 200


  # debug log
  sails.log.silly "res.ok() :: Sending 200 (\"OK\") response"

  if sendSocket

    verb = req.options.action
    model = req.options.controller

    if !data.message and !data.messages
      switch verb
        when"syncAds", "sync"
          data.message = "#{model} #{verb} From Facebook Success !"
        when "create", "update", "delete", "copy", "updateAd"
          data.message = "#{model} #{verb} Success !"

    req.socket.emit "message",
      verb: verb
      model: model
      data: data


  # If appropriate, serve data as JSON(P)
  if req.wantsJSON
    return res.jsonx(data)
  # If second argument is a string, we take that to mean it refers to a view.
  # If it was omitted, use an empty object (`{}`)
  options = if typeof options == 'string' then view: options else options or {}
  # If a view was provided in options, serve it.
  # Otherwise try to guess an appropriate view, or if that doesn't
  # work, just send JSON.
  return res.view options.view, data: data if options.view

  return res.guessView {data: data}, ->
    res.jsonx data

# ---
# generated by js2coffee 2.0.1
